// Shared classification rules and site metadata.
// Edit this file when adding new tags, domains, source names, or title patterns.
globalThis.AUTO_TAB_GROUPER_RULES = (() => {
const WEAK_TITLE_GROUPS = new Set(["教程", "视频", "论文", "文档", "API"]);
const FUNCTIONAL_TOPIC_STOP_WORDS = new Set([
  "a",
  "an",
  "and",
  "api",
  "app",
  "article",
  "blog",
  "csdn",
  "demo",
  "docs",
  "download",
  "downloads",
  "example",
  "github",
  "guide",
  "home",
  "install",
  "learn",
  "manual",
  "official",
  "page",
  "project",
  "readme",
  "release",
  "releases",
  "setup",
  "deploy",
  "deployment",
  "the",
  "tutorial",
  "video",
  "videos",
  "wiki",
  "zhihu",
  "下载",
  "安装",
  "配置",
  "教程",
  "文档",
  "指南",
  "手册",
  "官网",
  "博客",
  "项目",
  "工具",
  "使用",
  "部署",
  "搭建",
  "运行",
  "接入",
  "实战",
  "详解",
  "完整",
  "快速",
  "如何",
  "怎么",
  "本地",
  "相关",
  "资源",
  "页面",
  "视频",
  "源码"
]);

const SOURCE_NAME_PATTERN = "(?:csdn博客|csdn|知乎专栏|知乎|稀土掘金|掘金|博客园|简书|少数派|微信公众号|微信公众平台|公众号|哔哩哔哩|bilibili|b站|youtube|github|gitlab|gitee|stackoverflow|stack overflow|segmentfault|思否|开源中国|osc|infoq|medium|reddit|v2ex|腾讯云|阿里云|华为云|火山引擎|百度智能云|google|microsoft learn|mdn)";

const GROUP_COLORS = [
  "blue",
  "red",
  "yellow",
  "green",
  "pink",
  "purple",
  "cyan",
  "orange",
  "grey"
];

const DOMAIN_DISPLAY_NAMES = new Map([
  ["developer.chrome.com", "Chrome 开发者"],
  ["chromewebstore.google.com", "Chrome 商店"],
  ["apps.apple.com", "App Store"],
  ["developer.apple.com", "Apple 开发者"],
  ["appstoreconnect.apple.com", "App Store Connect"],
  ["github.com", "GitHub"],
  ["gitlab.com", "GitLab"],
  ["gitee.com", "Gitee"],
  ["stackoverflow.com", "Stack Overflow"],
  ["stackexchange.com", "Stack Exchange"],
  ["npmjs.com", "npm"],
  ["pypi.org", "PyPI"],
  ["crates.io", "crates.io"],
  ["csdn.net", "CSDN"],
  ["blog.csdn.net", "CSDN"],
  ["download.csdn.net", "CSDN"],
  ["juejin.cn", "掘金"],
  ["cnblogs.com", "博客园"],
  ["segmentfault.com", "SegmentFault"],
  ["oschina.net", "开源中国"],
  ["infoq.cn", "InfoQ"],
  ["infoq.com", "InfoQ"],
  ["v2ex.com", "V2EX"],
  ["google.com", "Google"],
  ["youtube.com", "YouTube"],
  ["youtu.be", "YouTube"],
  ["bilibili.com", "哔哩哔哩"],
  ["b23.tv", "哔哩哔哩"],
  ["bilibili.tv", "哔哩哔哩"],
  ["biliblii.com", "哔哩哔哩"],
  ["openai.com", "OpenAI"],
  ["platform.openai.com", "OpenAI API"],
  ["chatgpt.com", "ChatGPT"],
  ["anthropic.com", "Anthropic"],
  ["claude.ai", "Claude"],
  ["deepseek.com", "DeepSeek"],
  ["chat.deepseek.com", "DeepSeek"],
  ["platform.deepseek.com", "DeepSeek API"],
  ["moonshot.cn", "Kimi"],
  ["kimi.moonshot.cn", "Kimi"],
  ["qwen.ai", "通义千问"],
  ["tongyi.com", "通义千问"],
  ["doubao.com", "豆包"],
  ["volcengine.com", "火山引擎"],
  ["gemini.google.com", "Gemini"],
  ["grok.com", "Grok"],
  ["poe.com", "Poe"],
  ["huggingface.co", "Hugging Face"],
  ["ollama.com", "Ollama"],
  ["openwebui.com", "Open WebUI"],
  ["lmstudio.ai", "LM Studio"],
  ["langchain.com", "LangChain"],
  ["python.langchain.com", "LangChain"],
  ["llamaindex.ai", "LlamaIndex"],
  ["docs.llamaindex.ai", "LlamaIndex"],
  ["dify.ai", "Dify"],
  ["n8n.io", "n8n"],
  ["home-assistant.io", "Home Assistant"],
  ["neovim.io", "Neovim"],
  ["notion.so", "Notion"],
  ["obsidian.md", "Obsidian"],
  ["figma.com", "Figma"],
  ["framer.com", "Framer"],
  ["canva.com", "Canva"],
  ["linear.app", "Linear"],
  ["slack.com", "Slack"],
  ["discord.com", "Discord"],
  ["vercel.com", "Vercel"],
  ["supabase.com", "Supabase"],
  ["netlify.com", "Netlify"],
  ["x.com", "X"],
  ["twitter.com", "Twitter"],
  ["reddit.com", "Reddit"],
  ["zhihu.com", "知乎"],
  ["weibo.com", "微博"],
  ["xiaohongshu.com", "小红书"],
  ["taobao.com", "淘宝"],
  ["tmall.com", "天猫"],
  ["jd.com", "京东"],
  ["amazon.com", "Amazon"],
  ["amazon.cn", "Amazon"],
  ["baidu.com", "百度"],
  ["bing.com", "Bing"],
  ["duckduckgo.com", "DuckDuckGo"],
  ["perplexity.ai", "Perplexity"],
  ["medium.com", "Medium"],
  ["sspai.com", "少数派"],
  ["36kr.com", "36氪"],
  ["thepaper.cn", "澎湃新闻"],
  ["nytimes.com", "NYTimes"],
  ["reuters.com", "Reuters"],
  ["bbc.com", "BBC"],
  ["tradingview.com", "TradingView"],
  ["coursera.org", "Coursera"],
  ["udemy.com", "Udemy"],
  ["edx.org", "edX"],
  ["khanacademy.org", "Khan Academy"],
  ["macdown.uranusjr.com", "MacDown"],
  ["macdown.uranusjr.com.cn", "MacDown"]
]);

const PRODUCT_DOMAIN_GROUPS = new Set([
  "openai.com",
  "chatgpt.com",
  "anthropic.com",
  "claude.ai",
  "deepseek.com",
  "moonshot.cn",
  "qwen.ai",
  "tongyi.com",
  "doubao.com",
  "volcengine.com",
  "gemini.google.com",
  "grok.com",
  "poe.com",
  "perplexity.ai",
  "huggingface.co",
  "ollama.com",
  "openwebui.com",
  "lmstudio.ai",
  "langchain.com",
  "llamaindex.ai",
  "dify.ai",
  "n8n.io",
  "home-assistant.io",
  "neovim.io",
  "notion.so",
  "obsidian.md",
  "figma.com",
  "framer.com",
  "canva.com",
  "linear.app",
  "vercel.com",
  "supabase.com",
  "netlify.com",
  "cloudflare.com"
]);

const TITLE_TOPIC_RULES = [
  { group: "Rime 输入法", pattern: /\b(rime|librime|weasel|squirrel|trime|ibus-rime)\b|小狼毫|鼠须管|中州韵|雾凇拼音|薄荷拼音|朙月拼音|地球拼音|仓颉输入法|输入法方案/ },
  { group: "Chrome 扩展", pattern: /chrome\s*(extension|web store)|manifest\s*v?3|mv3|浏览器扩展|扩展程序|chrome 应用商店|chrome 商店/ },
  { group: "OpenAI API", pattern: /\b(openai|chatgpt|gpt-[45]|responses api|assistants api)\b.*\b(api|sdk|model|模型)\b|\b(api|sdk)\b.*\b(openai|gpt-[45])\b/ },
  { group: "OpenAI", pattern: /\b(openai|chatgpt|gpt-[45]|responses api|assistants api)\b/ },
  { group: "Claude", pattern: /\b(claude|anthropic)\b/ },
  { group: "DeepSeek API", pattern: /\bdeepseek\b.*\b(api|sdk|model|模型)\b|\b(api|sdk)\b.*\bdeepseek\b|deepseek.*接口/ },
  { group: "DeepSeek", pattern: /\bdeepseek\b|深度求索/ },
  { group: "Ollama", pattern: /\bollama\b/ },
  { group: "Open WebUI", pattern: /\bopen\s*webui\b/ },
  { group: "LM Studio", pattern: /\blm\s*studio\b/ },
  { group: "llama.cpp", pattern: /\bllama\.?cpp\b/ },
  { group: "vLLM", pattern: /\bvllm\b/ },
  { group: "LangChain", pattern: /\blangchain\b/ },
  { group: "LlamaIndex", pattern: /\bllamaindex\b|llama\s*index/ },
  { group: "Dify", pattern: /\bdify\b/ },
  { group: "n8n", pattern: /\bn8n\b/ },
  { group: "Kimi", pattern: /\bkimi\b|moonshot|月之暗面/ },
  { group: "通义千问", pattern: /\bqwen\b|通义千问|通义\b/ },
  { group: "豆包", pattern: /\bdoubao\b|豆包|火山方舟/ },
  { group: "Gemini", pattern: /\bgemini\b|google ai studio/ },
  { group: "Grok", pattern: /\bgrok\b/ },
  { group: "Perplexity", pattern: /\bperplexity\b/ },
  { group: "Hugging Face", pattern: /\bhugging\s*face\b|transformers|diffusers/ },
  { group: "Midjourney", pattern: /\bmidjourney\b/ },
  { group: "Stable Diffusion", pattern: /\bstable diffusion\b|\bsdxl\b|comfyui|automatic1111/ },
  { group: "大模型", pattern: /\bllm\b|大语言模型|提示词|prompt engineering|rag\b|向量数据库|embedding|推理模型/ },
  { group: "Cursor", pattern: /\bcursor\b/ },
  { group: "VS Code", pattern: /\b(vs ?code|visual studio code)\b/ },
  { group: "Neovim", pattern: /\bneovim\b|\bnvim\b/ },
  { group: "React", pattern: /\breact(?:\.js)?\b/ },
  { group: "Vue", pattern: /\bvue(?:\.js)?\b/ },
  { group: "Next.js", pattern: /\bnext(?:\.js)?\b/ },
  { group: "Nuxt", pattern: /\bnuxt(?:\.js)?\b/ },
  { group: "Svelte", pattern: /\bsvelte(?:kit)?\b/ },
  { group: "Angular", pattern: /\bangular\b/ },
  { group: "Astro", pattern: /\bastro\b/ },
  { group: "Tailwind CSS", pattern: /\btailwind(?:css)?\b/ },
  { group: "TypeScript", pattern: /\btypescript|tsconfig\b/ },
  { group: "JavaScript", pattern: /\bjavascript|node\.js|npm|pnpm|yarn|bun\b/ },
  { group: "Python", pattern: /\bpython|pyenv|pip|conda|jupyter|fastapi|django|flask\b/ },
  { group: "Rust", pattern: /\brust|cargo|tokio|tauri\b/ },
  { group: "Go", pattern: /\bgolang\b|\bgo语言\b/ },
  { group: "Swift", pattern: /\bswift|swiftui|xcode\b/ },
  { group: "HarmonyOS", pattern: /harmonyos|鸿蒙|arkts|arkui|deveco/ },
  { group: "Docker", pattern: /\bdocker|dockerfile|docker compose|compose\.ya?ml\b/ },
  { group: "Kubernetes", pattern: /\bkubernetes|k8s|kubectl|helm\b/ },
  { group: "Git", pattern: /\bgit\b|版本控制/ },
  { group: "GitHub Actions", pattern: /github actions|\bgha\b/ },
  { group: "Cloudflare", pattern: /\bcloudflare\b|workers? pages|cloudflare workers/ },
  { group: "Home Assistant", pattern: /\bhome assistant\b|\bhaos\b/ },
  { group: "PostgreSQL", pattern: /\bpostgres(?:ql)?\b/ },
  { group: "Supabase", pattern: /\bsupabase\b/ },
  { group: "Redis", pattern: /\bredis\b/ },
  { group: "MongoDB", pattern: /\bmongodb|mongo\b/ },
  { group: "API", pattern: /\b(rest api|graphql|grpc|openapi|swagger|webhook)\b|接口文档/ },
  { group: "macOS", pattern: /\bmacos|launchd|homebrew|brew\b|快捷指令|自动操作/ },
  { group: "Windows", pattern: /\bwindows|powershell|wsl\b/ },
  { group: "Linux", pattern: /\blinux|ubuntu|debian|archlinux|systemd\b/ },
  { group: "Markdown", pattern: /\bmarkdown|mdx\b/ },
  { group: "Obsidian", pattern: /\bobsidian\b/ },
  { group: "Notion", pattern: /\bnotion\b/ },
  { group: "LaTeX", pattern: /\blatex|overleaf\b/ },
  { group: "MacDown", pattern: /\bmacdown\b/ },
  { group: "MarkEdit", pattern: /\bmarkedit\b/ },
  { group: "论文", pattern: /论文|paper|arxiv|doi\.org|research/ },
  { group: "文档", pattern: /文档|documentation|docs|manual|reference|手册/ },
  { group: "教程", pattern: /教程|入门|指南|guide|tutorial|learn/ },
  { group: "视频", pattern: /视频|直播|回放|\bvideo\b|\blive\b/ }
];

const SITE_PROPERTY_RULES = [
  { group: "AI", domains: ["chat.openai.com", "chatgpt.com", "openai.com", "platform.openai.com", "claude.ai", "anthropic.com", "deepseek.com", "chat.deepseek.com", "platform.deepseek.com", "kimi.moonshot.cn", "moonshot.cn", "qwen.ai", "tongyi.com", "doubao.com", "volcengine.com", "gemini.google.com", "aistudio.google.com", "grok.com", "poe.com", "perplexity.ai", "huggingface.co", "ollama.com", "openwebui.com", "lmstudio.ai", "langchain.com", "llamaindex.ai", "dify.ai"] },
  { group: "文档", domains: ["developer.mozilla.org", "docs.github.com", "learn.microsoft.com", "devdocs.io", "readthedocs.io", "developer.chrome.com", "developer.apple.com", "platform.openai.com", "docs.anthropic.com", "docs.cursor.com", "docs.deepseek.com", "docs.ollama.com", "docs.openwebui.com", "python.langchain.com", "docs.llamaindex.ai", "docs.dify.ai", "docs.n8n.io", "react.dev", "vuejs.org", "nextjs.org", "nuxt.com", "svelte.dev", "astro.build", "tailwindcss.com", "vite.dev", "nodejs.org", "docs.python.org", "doc.rust-lang.org", "go.dev", "developer.harmonyos.com"] },
  { group: "代码", domains: ["github.com", "gitlab.com", "bitbucket.org", "gitee.com", "stackoverflow.com", "stackexchange.com", "npmjs.com", "pypi.org", "crates.io", "pkg.go.dev"] },
  { group: "视频", domains: ["youtube.com", "youtu.be", "bilibili.com", "b23.tv", "bilibili.tv", "vimeo.com", "netflix.com", "iqiyi.com", "youku.com", "tencentvideo.com", "douyin.com", "tiktok.com", "kuaishou.com"] },
  { group: "邮箱", domains: ["mail.google.com", "outlook.live.com", "outlook.office.com", "mail.qq.com", "mail.163.com", "mail.126.com"] },
  { group: "应用商店", domains: ["chromewebstore.google.com", "apps.apple.com", "appstoreconnect.apple.com"] },
  { group: "办公", domains: ["notion.so", "docs.google.com", "drive.google.com", "office.com", "feishu.cn", "larksuite.com", "yuque.com", "linear.app", "slack.com", "n8n.io"] },
  { group: "设计", domains: ["figma.com", "dribbble.com", "behance.net", "canva.com", "framer.com"] },
  { group: "学习", domains: ["coursera.org", "udemy.com", "edx.org", "khanacademy.org", "leetcode.com", "freecodecamp.org"] },
  { group: "部署", domains: ["vercel.com", "netlify.com", "cloudflare.com", "render.com", "railway.app"] },
  { group: "购物", domains: ["amazon.com", "amazon.cn", "taobao.com", "tmall.com", "jd.com", "pinduoduo.com", "1688.com", "ebay.com"] },
  { group: "社交", domains: ["x.com", "twitter.com", "facebook.com", "instagram.com", "weibo.com", "discord.com"] },
  { group: "新闻", domains: ["news.ycombinator.com", "nytimes.com", "bbc.com", "reuters.com", "thepaper.cn", "36kr.com", "sspai.com"] },
  { group: "金融", domains: ["finance.yahoo.com", "tradingview.com", "bloomberg.com", "eastmoney.com", "xueqiu.com"] },
  { group: "搜索", domains: ["google.com", "bing.com", "baidu.com", "duckduckgo.com"] }
];

const MULTI_PART_TLDS = new Set([
  "co.uk",
  "org.uk",
  "ac.uk",
  "gov.uk",
  "com.cn",
  "net.cn",
  "org.cn",
  "gov.cn",
  "com.au",
  "net.au",
  "org.au",
  "co.jp",
  "co.kr",
  "com.br",
  "com.mx",
  "com.sg",
  "com.hk",
  "com.tw"
]);

  return {
    WEAK_TITLE_GROUPS,
    FUNCTIONAL_TOPIC_STOP_WORDS,
    SOURCE_NAME_PATTERN,
    GROUP_COLORS,
    DOMAIN_DISPLAY_NAMES,
    PRODUCT_DOMAIN_GROUPS,
    TITLE_TOPIC_RULES,
    SITE_PROPERTY_RULES,
    MULTI_PART_TLDS
  };
})();
