// Shared classification rules and site metadata.
// Edit this file when adding new tags, domains, source names, or title patterns.
globalThis.AUTO_TAB_GROUPER_RULES = (() => {
const WEAK_TITLE_GROUPS = new Set(["教程", "视频", "论文", "文档", "API"]);
const FUNCTIONAL_TOPIC_STOP_WORDS = new Set([
  "a",
  "an",
  "and",
  "api",
  "app",
  "article",
  "blog",
  "csdn",
  "demo",
  "docs",
  "download",
  "downloads",
  "dashboard",
  "example",
  "forum",
  "github",
  "guide",
  "home",
  "install",
  "learn",
  "manual",
  "official",
  "page",
  "project",
  "readme",
  "release",
  "releases",
  "review",
  "setup",
  "signin",
  "sign in",
  "sign up",
  "deploy",
  "deployment",
  "the",
  "tutorial",
  "video",
  "videos",
  "wiki",
  "zhihu",
  "下载",
  "安装",
  "配置",
  "教程",
  "文档",
  "指南",
  "手册",
  "官网",
  "博客",
  "控制台",
  "登录",
  "注册",
  "项目",
  "工具",
  "使用",
  "评测",
  "测评",
  "部署",
  "搭建",
  "运行",
  "接入",
  "实战",
  "详解",
  "完整",
  "快速",
  "如何",
  "怎么",
  "本地",
  "相关",
  "资源",
  "页面",
  "视频",
  "源码"
]);

const SOURCE_NAME_PATTERN = "(?:csdn博客|csdn|知乎专栏|知乎|Quora|Reddit|贴吧|百度贴吧|豆瓣|稀土掘金|掘金|博客园|简书|少数派|微信公众号|微信公众平台|公众号|QQ空间|腾讯视频|腾讯文档|腾讯会议|腾讯新闻|腾讯体育|腾讯动漫|腾讯云|腾讯元宝|腾讯混元|企业微信|微信读书|QQ音乐|QQ邮箱|哔哩哔哩|哔哩哔哩视频|bilibili|b站|B站|抖音|douyin|tiktok|快手|kuaishou|小红书|爱奇艺|优酷|西瓜视频|AcFun|芒果TV|youtube|vimeo|github|gitlab|gitee|bitbucket|stackoverflow|stack overflow|segmentfault|思否|开源中国|osc|infoq|medium|dev\\.to|reddit|v2ex|Hacker News|Product Hunt|Apple 支持|Apple 开发者|App Store|Apple Music|Apple TV|iCloud|Apple|阿里云|华为云|火山引擎|百度智能云|七牛云|又拍云|google|bing|百度搜索|百度|duckduckgo|microsoft learn|mdn|mozilla|aws|azure|cloudflare|vercel|netlify|render|railway)";

const GROUP_COLORS = [
  "blue",
  "red",
  "yellow",
  "green",
  "pink",
  "purple",
  "cyan",
  "orange",
  "grey"
];

const FUNCTIONAL_SITE_GROUPS = new Set(["邮箱", "聊天"]);

const CLOUD_FINE_GRAINED_GROUPS = new Set([
  "GitHub",
  "GitLab",
  "Gitee",
  "Bitbucket",
  "Stack Overflow",
  "Stack Exchange",
  "YouTube",
  "Vimeo",
  "哔哩哔哩",
  "哔哩哔哩直播",
  "抖音",
  "快手",
  "小红书",
  "知乎",
  "Quora",
  "CSDN",
  "掘金",
  "博客园",
  "V2EX",
  "Reddit",
  "Medium",
  "DEV",
  "Hacker News",
  "Product Hunt",
  "百度贴吧",
  "豆瓣",
  "搜索",
  "Google",
  "Bing",
  "百度",
  "DuckDuckGo",
  "Kagi",
  "Brave Search"
]);

const SEARCH_ENGINE_DOMAINS = new Set([
  "google.com",
  "bing.com",
  "baidu.com",
  "duckduckgo.com",
  "kagi.com",
  "search.brave.com",
  "startpage.com",
  "ecosia.org",
  "yandex.com",
  "search.yahoo.com",
  "sogou.com",
  "so.com",
  "mijisou.com",
  "quark.cn",
  "sm.cn",
  "naver.com",
  "searx.space",
  "perplexity.ai"
]);

const DOMAIN_DISPLAY_NAMES = new Map([
  ["developer.chrome.com", "Chrome 开发者"],
  ["chromewebstore.google.com", "Chrome 商店"],
  ["apple.com", "Apple"],
  ["www.apple.com", "Apple"],
  ["apps.apple.com", "App Store"],
  ["developer.apple.com", "Apple 开发者"],
  ["appstoreconnect.apple.com", "App Store Connect"],
  ["support.apple.com", "Apple 支持"],
  ["discussions.apple.com", "Apple 社区"],
  ["icloud.com", "iCloud"],
  ["www.icloud.com", "iCloud"],
  ["music.apple.com", "Apple Music"],
  ["tv.apple.com", "Apple TV"],
  ["podcasts.apple.com", "Apple 播客"],
  ["books.apple.com", "Apple Books"],
  ["developer.apple.com.cn", "Apple 开发者"],
  ["github.com", "GitHub"],
  ["gitlab.com", "GitLab"],
  ["gitee.com", "Gitee"],
  ["bitbucket.org", "Bitbucket"],
  ["sourceforge.net", "SourceForge"],
  ["codeberg.org", "Codeberg"],
  ["stackoverflow.com", "Stack Overflow"],
  ["stackexchange.com", "Stack Exchange"],
  ["superuser.com", "Super User"],
  ["serverfault.com", "Server Fault"],
  ["npmjs.com", "npm"],
  ["jsr.io", "JSR"],
  ["deno.land", "Deno"],
  ["pypi.org", "PyPI"],
  ["crates.io", "crates.io"],
  ["pkg.go.dev", "Go Packages"],
  ["mvnrepository.com", "Maven Repository"],
  ["packagist.org", "Packagist"],
  ["rubygems.org", "RubyGems"],
  ["pub.dev", "pub.dev"],
  ["nuget.org", "NuGet"],
  ["docker.com", "Docker"],
  ["hub.docker.com", "Docker Hub"],
  ["csdn.net", "CSDN"],
  ["blog.csdn.net", "CSDN"],
  ["download.csdn.net", "CSDN"],
  ["juejin.cn", "掘金"],
  ["dev.to", "DEV"],
  ["cnblogs.com", "博客园"],
  ["segmentfault.com", "SegmentFault"],
  ["oschina.net", "开源中国"],
  ["infoq.cn", "InfoQ"],
  ["infoq.com", "InfoQ"],
  ["v2ex.com", "V2EX"],
  ["qq.com", "腾讯"],
  ["qzone.qq.com", "QQ 空间"],
  ["user.qzone.qq.com", "QQ 空间"],
  ["i.qq.com", "QQ 空间"],
  ["mail.qq.com", "QQ 邮箱"],
  ["exmail.qq.com", "腾讯企业邮箱"],
  ["v.qq.com", "腾讯视频"],
  ["video.qq.com", "腾讯视频"],
  ["film.qq.com", "腾讯视频"],
  ["sports.qq.com", "腾讯体育"],
  ["news.qq.com", "腾讯新闻"],
  ["new.qq.com", "腾讯新闻"],
  ["docs.qq.com", "腾讯文档"],
  ["y.qq.com", "QQ 音乐"],
  ["music.qq.com", "QQ 音乐"],
  ["kg.qq.com", "全民 K 歌"],
  ["ac.qq.com", "腾讯动漫"],
  ["im.qq.com", "QQ"],
  ["weixin.qq.com", "微信"],
  ["mp.weixin.qq.com", "微信公众平台"],
  ["work.weixin.qq.com", "企业微信"],
  ["wx.qq.com", "微信网页版"],
  ["weread.qq.com", "微信读书"],
  ["tencent.com", "腾讯"],
  ["cloud.tencent.com", "腾讯云"],
  ["console.cloud.tencent.com", "腾讯云"],
  ["meeting.tencent.com", "腾讯会议"],
  ["hunyuan.tencent.com", "腾讯混元"],
  ["yuanbao.tencent.com", "腾讯元宝"],
  ["voovmeeting.com", "腾讯会议"],
  ["weiyun.com", "腾讯微云"],
  ["tencentvideo.com", "腾讯视频"],
  ["google.com", "Google"],
  ["gmail.com", "Gmail"],
  ["mail.google.com", "Gmail"],
  ["docs.google.com", "Google Docs"],
  ["drive.google.com", "Google Drive"],
  ["calendar.google.com", "Google Calendar"],
  ["meet.google.com", "Google Meet"],
  ["colab.research.google.com", "Google Colab"],
  ["cloud.google.com", "Google Cloud"],
  ["console.cloud.google.com", "Google Cloud"],
  ["firebase.google.com", "Firebase"],
  ["chat.google.com", "Google Chat"],
  ["messages.google.com", "Google Messages"],
  ["youtube.com", "YouTube"],
  ["youtu.be", "YouTube"],
  ["bilibili.com", "哔哩哔哩"],
  ["search.bilibili.com", "哔哩哔哩"],
  ["space.bilibili.com", "哔哩哔哩"],
  ["live.bilibili.com", "哔哩哔哩直播"],
  ["bangumi.bilibili.com", "哔哩哔哩番剧"],
  ["t.bilibili.com", "哔哩哔哩动态"],
  ["b23.tv", "哔哩哔哩"],
  ["bilibili.tv", "哔哩哔哩"],
  ["biliblii.com", "哔哩哔哩"],
  ["douyin.com", "抖音"],
  ["v.douyin.com", "抖音"],
  ["live.douyin.com", "抖音直播"],
  ["iesdouyin.com", "抖音"],
  ["tiktok.com", "TikTok"],
  ["vm.tiktok.com", "TikTok"],
  ["kuaishou.com", "快手"],
  ["live.kuaishou.com", "快手直播"],
  ["gifshow.com", "快手"],
  ["xiaohongshu.com", "小红书"],
  ["xhslink.com", "小红书"],
  ["iqiyi.com", "爱奇艺"],
  ["youku.com", "优酷"],
  ["mgtv.com", "芒果 TV"],
  ["ixigua.com", "西瓜视频"],
  ["acfun.cn", "AcFun"],
  ["openai.com", "OpenAI"],
  ["platform.openai.com", "OpenAI API"],
  ["api.openai.com", "OpenAI API"],
  ["docs.openai.com", "OpenAI 文档"],
  ["chatgpt.com", "ChatGPT"],
  ["anthropic.com", "Anthropic"],
  ["docs.anthropic.com", "Anthropic 文档"],
  ["claude.ai", "Claude"],
  ["deepseek.com", "DeepSeek"],
  ["chat.deepseek.com", "DeepSeek"],
  ["platform.deepseek.com", "DeepSeek API"],
  ["api-docs.deepseek.com", "DeepSeek 文档"],
  ["moonshot.cn", "Kimi"],
  ["kimi.moonshot.cn", "Kimi"],
  ["qwen.ai", "通义千问"],
  ["tongyi.com", "通义千问"],
  ["doubao.com", "豆包"],
  ["volcengine.com", "火山引擎"],
  ["console.volcengine.com", "火山引擎"],
  ["ark.cn-beijing.volces.com", "火山方舟"],
  ["gemini.google.com", "Gemini"],
  ["grok.com", "Grok"],
  ["poe.com", "Poe"],
  ["huggingface.co", "Hugging Face"],
  ["ollama.com", "Ollama"],
  ["openwebui.com", "Open WebUI"],
  ["lmstudio.ai", "LM Studio"],
  ["langchain.com", "LangChain"],
  ["python.langchain.com", "LangChain"],
  ["llamaindex.ai", "LlamaIndex"],
  ["docs.llamaindex.ai", "LlamaIndex"],
  ["dify.ai", "Dify"],
  ["n8n.io", "n8n"],
  ["home-assistant.io", "Home Assistant"],
  ["neovim.io", "Neovim"],
  ["notion.so", "Notion"],
  ["obsidian.md", "Obsidian"],
  ["figma.com", "Figma"],
  ["framer.com", "Framer"],
  ["canva.com", "Canva"],
  ["linear.app", "Linear"],
  ["slack.com", "Slack"],
  ["discord.com", "Discord"],
  ["vercel.com", "Vercel"],
  ["supabase.com", "Supabase"],
  ["netlify.com", "Netlify"],
  ["x.com", "X"],
  ["twitter.com", "Twitter"],
  ["reddit.com", "Reddit"],
  ["old.reddit.com", "Reddit"],
  ["www.reddit.com", "Reddit"],
  ["quora.com", "Quora"],
  ["www.quora.com", "Quora"],
  ["zhihu.com", "知乎"],
  ["www.zhihu.com", "知乎"],
  ["zhuanlan.zhihu.com", "知乎专栏"],
  ["tieba.baidu.com", "百度贴吧"],
  ["douban.com", "豆瓣"],
  ["www.douban.com", "豆瓣"],
  ["groups.google.com", "Google Groups"],
  ["discourse.org", "Discourse"],
  ["news.ycombinator.com", "Hacker News"],
  ["weibo.com", "微博"],
  ["taobao.com", "淘宝"],
  ["tmall.com", "天猫"],
  ["jd.com", "京东"],
  ["amazon.com", "Amazon"],
  ["amazon.cn", "Amazon"],
  ["baidu.com", "百度"],
  ["bing.com", "Bing"],
  ["duckduckgo.com", "DuckDuckGo"],
  ["kagi.com", "Kagi"],
  ["search.brave.com", "Brave Search"],
  ["startpage.com", "Startpage"],
  ["ecosia.org", "Ecosia"],
  ["yandex.com", "Yandex"],
  ["search.yahoo.com", "Yahoo Search"],
  ["sogou.com", "搜狗"],
  ["so.com", "360 搜索"],
  ["mijisou.com", "秘迹搜索"],
  ["quark.cn", "夸克"],
  ["sm.cn", "神马搜索"],
  ["naver.com", "Naver"],
  ["outlook.live.com", "Outlook"],
  ["outlook.office.com", "Outlook"],
  ["outlook.office365.com", "Outlook"],
  ["mail.yahoo.com", "Yahoo Mail"],
  ["proton.me", "Proton"],
  ["mail.proton.me", "Proton Mail"],
  ["protonmail.com", "Proton Mail"],
  ["mail.zoho.com", "Zoho Mail"],
  ["mail.163.com", "网易邮箱"],
  ["mail.126.com", "网易邮箱"],
  ["mail.sina.com.cn", "新浪邮箱"],
  ["mail.sohu.com", "搜狐邮箱"],
  ["mail.aliyun.com", "阿里邮箱"],
  ["web.whatsapp.com", "WhatsApp"],
  ["telegram.org", "Telegram"],
  ["web.telegram.org", "Telegram"],
  ["webk.telegram.org", "Telegram"],
  ["webz.telegram.org", "Telegram"],
  ["app.slack.com", "Slack"],
  ["teams.microsoft.com", "Microsoft Teams"],
  ["teams.live.com", "Microsoft Teams"],
  ["web.skype.com", "Skype"],
  ["messenger.com", "Messenger"],
  ["www.messenger.com", "Messenger"],
  ["web.line.me", "LINE"],
  ["line.me", "LINE"],
  ["app.element.io", "Element"],
  ["matrix.to", "Matrix"],
  ["web.dingtalk.com", "钉钉"],
  ["im.dingtalk.com", "钉钉"],
  ["feishu.cn", "飞书"],
  ["larksuite.com", "Lark"],
  ["perplexity.ai", "Perplexity"],
  ["copilot.microsoft.com", "Microsoft Copilot"],
  ["microsoft.com", "Microsoft"],
  ["meta.ai", "Meta AI"],
  ["mistral.ai", "Mistral"],
  ["chat.mistral.ai", "Le Chat"],
  ["groq.com", "Groq"],
  ["console.groq.com", "Groq"],
  ["phind.com", "Phind"],
  ["you.com", "You.com"],
  ["character.ai", "Character.AI"],
  ["replicate.com", "Replicate"],
  ["cohere.com", "Cohere"],
  ["together.ai", "Together AI"],
  ["openrouter.ai", "OpenRouter"],
  ["fireworks.ai", "Fireworks AI"],
  ["anyscale.com", "Anyscale"],
  ["cursor.com", "Cursor"],
  ["codeium.com", "Codeium"],
  ["windsurf.com", "Windsurf"],
  ["lovable.dev", "Lovable"],
  ["bolt.new", "Bolt"],
  ["v0.dev", "v0"],
  ["siliconflow.cn", "硅基流动"],
  ["modelscope.cn", "魔搭社区"],
  ["ai.google.dev", "Google AI"],
  ["aistudio.google.com", "Google AI Studio"],
  ["civitai.com", "Civitai"],
  ["midjourney.com", "Midjourney"],
  ["stability.ai", "Stability AI"],
  ["runwayml.com", "Runway"],
  ["medium.com", "Medium"],
  ["sspai.com", "少数派"],
  ["36kr.com", "36氪"],
  ["thepaper.cn", "澎湃新闻"],
  ["nytimes.com", "NYTimes"],
  ["reuters.com", "Reuters"],
  ["bbc.com", "BBC"],
  ["tradingview.com", "TradingView"],
  ["finance.yahoo.com", "Yahoo Finance"],
  ["bloomberg.com", "Bloomberg"],
  ["eastmoney.com", "东方财富"],
  ["xueqiu.com", "雪球"],
  ["coursera.org", "Coursera"],
  ["udemy.com", "Udemy"],
  ["edx.org", "edX"],
  ["khanacademy.org", "Khan Academy"],
  ["leetcode.com", "LeetCode"],
  ["freecodecamp.org", "freeCodeCamp"],
  ["duolingo.com", "Duolingo"],
  ["wikipedia.org", "Wikipedia"],
  ["zh.wikipedia.org", "Wikipedia"],
  ["arxiv.org", "arXiv"],
  ["scholar.google.com", "Google Scholar"],
  ["overleaf.com", "Overleaf"],
  ["figma.com", "Figma"],
  ["miro.com", "Miro"],
  ["notion.so", "Notion"],
  ["notion.site", "Notion"],
  ["yuque.com", "语雀"],
  ["wolai.com", "我来"],
  ["quip.com", "Quip"],
  ["trello.com", "Trello"],
  ["asana.com", "Asana"],
  ["jira.atlassian.com", "Jira"],
  ["atlassian.com", "Atlassian"],
  ["confluence.atlassian.com", "Confluence"],
  ["mi.com", "小米"],
  ["huawei.com", "华为"],
  ["cloud.huawei.com", "华为云"],
  ["huaweicloud.com", "华为云"],
  ["aliyun.com", "阿里云"],
  ["console.aliyun.com", "阿里云"],
  ["alibabacloud.com", "阿里云"],
  ["amazonaws.com", "AWS"],
  ["aws.amazon.com", "AWS"],
  ["console.aws.amazon.com", "AWS"],
  ["azure.microsoft.com", "Azure"],
  ["portal.azure.com", "Azure"],
  ["digitalocean.com", "DigitalOcean"],
  ["heroku.com", "Heroku"],
  ["railway.app", "Railway"],
  ["render.com", "Render"],
  ["fly.io", "Fly.io"],
  ["sentry.io", "Sentry"],
  ["datadoghq.com", "Datadog"],
  ["grafana.com", "Grafana"],
  ["prometheus.io", "Prometheus"],
  ["elastic.co", "Elastic"],
  ["postman.com", "Postman"],
  ["apifox.com", "Apifox"],
  ["insomnia.rest", "Insomnia"],
  ["linear.app", "Linear"],
  ["macdown.uranusjr.com", "MacDown"],
  ["macdown.uranusjr.com.cn", "MacDown"]
]);

const PRODUCT_DOMAIN_GROUPS = new Set([
  "github.com",
  "gitlab.com",
  "gitee.com",
  "bitbucket.org",
  "sourceforge.net",
  "codeberg.org",
  "reddit.com",
  "quora.com",
  "zhihu.com",
  "v2ex.com",
  "tieba.baidu.com",
  "douban.com",
  "openai.com",
  "chatgpt.com",
  "anthropic.com",
  "claude.ai",
  "deepseek.com",
  "qq.com",
  "tencent.com",
  "weiyun.com",
  "voovmeeting.com",
  "tencentvideo.com",
  "youtube.com",
  "youtu.be",
  "bilibili.com",
  "b23.tv",
  "bilibili.tv",
  "douyin.com",
  "iesdouyin.com",
  "tiktok.com",
  "kuaishou.com",
  "gifshow.com",
  "xiaohongshu.com",
  "xhslink.com",
  "iqiyi.com",
  "youku.com",
  "mgtv.com",
  "ixigua.com",
  "acfun.cn",
  "apple.com",
  "icloud.com",
  "moonshot.cn",
  "qwen.ai",
  "tongyi.com",
  "doubao.com",
  "volcengine.com",
  "gemini.google.com",
  "grok.com",
  "poe.com",
  "perplexity.ai",
  "copilot.microsoft.com",
  "meta.ai",
  "mistral.ai",
  "chat.mistral.ai",
  "groq.com",
  "phind.com",
  "you.com",
  "character.ai",
  "replicate.com",
  "cohere.com",
  "together.ai",
  "openrouter.ai",
  "fireworks.ai",
  "cursor.com",
  "codeium.com",
  "windsurf.com",
  "lovable.dev",
  "bolt.new",
  "v0.dev",
  "civitai.com",
  "midjourney.com",
  "stability.ai",
  "runwayml.com",
  "siliconflow.cn",
  "modelscope.cn",
  "huggingface.co",
  "ollama.com",
  "openwebui.com",
  "lmstudio.ai",
  "langchain.com",
  "llamaindex.ai",
  "dify.ai",
  "n8n.io",
  "home-assistant.io",
  "neovim.io",
  "notion.so",
  "obsidian.md",
  "figma.com",
  "framer.com",
  "canva.com",
  "linear.app",
  "vercel.com",
  "supabase.com",
  "netlify.com",
  "cloudflare.com",
  "firebase.google.com",
  "cloud.google.com",
  "aws.amazon.com",
  "amazonaws.com",
  "azure.microsoft.com",
  "portal.azure.com",
  "aliyun.com",
  "huaweicloud.com",
  "digitalocean.com",
  "railway.app",
  "render.com",
  "fly.io",
  "sentry.io",
  "postman.com",
  "apifox.com",
  "insomnia.rest",
  "leetcode.com",
  "wikipedia.org",
  "arxiv.org",
  "overleaf.com",
  "miro.com",
  "yuque.com",
  "trello.com",
  "asana.com",
  "atlassian.com"
]);

const TITLE_TOPIC_RULES = [
  { group: "Rime 输入法", pattern: /\b(rime|librime|weasel|squirrel|trime|ibus-rime)\b|小狼毫|鼠须管|中州韵|雾凇拼音|薄荷拼音|朙月拼音|地球拼音|仓颉输入法|输入法方案/ },
  { group: "Chrome 扩展", pattern: /chrome\s*(extension|web store)|manifest\s*v?3|mv3|浏览器扩展|扩展程序|chrome 应用商店|chrome 商店/ },
  { group: "App Store", pattern: /\bapp store\b|苹果应用商店|testflight|appstoreconnect|app store connect/ },
  { group: "Apple 开发者", pattern: /apple developer|developer\.apple|苹果开发者|swiftui|xcode|testflight|app store connect/ },
  { group: "Apple 支持", pattern: /apple support|support\.apple|苹果支持|苹果客服|apple 社区|apple discussions/ },
  { group: "Apple Music", pattern: /apple music|苹果音乐/ },
  { group: "Apple TV", pattern: /apple tv|苹果 tv/ },
  { group: "iCloud", pattern: /\bicloud\b|苹果云/ },
  { group: "OpenAI API", pattern: /\b(openai|chatgpt|gpt-[45]|responses api|assistants api)\b.*\b(api|sdk|model|模型)\b|\b(api|sdk)\b.*\b(openai|gpt-[45])\b/ },
  { group: "OpenAI", pattern: /\b(openai|chatgpt|gpt-[45]|responses api|assistants api)\b/ },
  { group: "Claude", pattern: /\b(claude|anthropic)\b/ },
  { group: "DeepSeek API", pattern: /\bdeepseek\b.*\b(api|sdk|model|模型)\b|\b(api|sdk)\b.*\bdeepseek\b|deepseek.*接口/ },
  { group: "DeepSeek", pattern: /\bdeepseek\b|深度求索/ },
  { group: "Ollama", pattern: /\bollama\b/ },
  { group: "Open WebUI", pattern: /\bopen\s*webui\b/ },
  { group: "LM Studio", pattern: /\blm\s*studio\b/ },
  { group: "llama.cpp", pattern: /\bllama\.?cpp\b/ },
  { group: "vLLM", pattern: /\bvllm\b/ },
  { group: "LangChain", pattern: /\blangchain\b/ },
  { group: "LlamaIndex", pattern: /\bllamaindex\b|llama\s*index/ },
  { group: "Dify", pattern: /\bdify\b/ },
  { group: "n8n", pattern: /\bn8n\b/ },
  { group: "Kimi", pattern: /\bkimi\b|moonshot|月之暗面/ },
  { group: "通义千问", pattern: /\bqwen\b|通义千问|通义\b/ },
  { group: "豆包", pattern: /\bdoubao\b|豆包|火山方舟/ },
  { group: "Gemini", pattern: /\bgemini\b|google ai studio/ },
  { group: "Grok", pattern: /\bgrok\b/ },
  { group: "Perplexity", pattern: /\bperplexity\b/ },
  { group: "Microsoft Copilot", pattern: /\bcopilot\b|microsoft copilot/ },
  { group: "Meta AI", pattern: /\bmeta ai\b/ },
  { group: "Mistral", pattern: /\bmistral\b|le chat/ },
  { group: "Groq", pattern: /\bgroq\b/ },
  { group: "Phind", pattern: /\bphind\b/ },
  { group: "You.com", pattern: /\byou\.com\b|\byou ai\b/ },
  { group: "Character.AI", pattern: /character\.ai|character ai/ },
  { group: "Replicate", pattern: /\breplicate\b/ },
  { group: "Cohere", pattern: /\bcohere\b/ },
  { group: "Together AI", pattern: /together ai|\btogether\.ai\b/ },
  { group: "OpenRouter", pattern: /\bopenrouter\b/ },
  { group: "Fireworks AI", pattern: /\bfireworks ai\b|\bfireworks\.ai\b/ },
  { group: "硅基流动", pattern: /硅基流动|siliconflow/ },
  { group: "魔搭社区", pattern: /魔搭|modelscope/ },
  { group: "Hugging Face", pattern: /\bhugging\s*face\b|transformers|diffusers/ },
  { group: "Civitai", pattern: /\bcivitai\b/ },
  { group: "Midjourney", pattern: /\bmidjourney\b/ },
  { group: "Stable Diffusion", pattern: /\bstable diffusion\b|\bsdxl\b|\bsd3\b|comfyui|automatic1111|stable-diffusion-webui/ },
  { group: "Runway", pattern: /\brunway\b|runwayml/ },
  { group: "AI 图像", pattern: /文生图|图生图|ai绘画|ai 绘画|扩散模型|controlnet|lora\b|flux\b/ },
  { group: "RAG", pattern: /\brag\b|检索增强|向量检索|知识库问答|embedding|embeddings|rerank|重排序|向量数据库/ },
  { group: "Prompt", pattern: /提示词|prompt engineering|system prompt|prompt injection|提示工程/ },
  { group: "大模型", pattern: /\bllm\b|\bllms\b|大语言模型|多模态模型|推理模型|function calling|tool calls?|上下文窗口/ },
  { group: "Cursor", pattern: /\bcursor\b/ },
  { group: "Windsurf", pattern: /\bwindsurf\b/ },
  { group: "Codeium", pattern: /\bcodeium\b/ },
  { group: "Lovable", pattern: /\blovable\b/ },
  { group: "Bolt", pattern: /\bbolt\.new\b|\bstackblitz\b/ },
  { group: "v0", pattern: /\bv0\.dev\b|\bvercel v0\b/ },
  { group: "VS Code", pattern: /\b(vs ?code|visual studio code)\b/ },
  { group: "JetBrains", pattern: /\bjetbrains\b|intellij idea|webstorm|pycharm|goland|clion|rider\b/ },
  { group: "Neovim", pattern: /\bneovim\b|\bnvim\b/ },
  { group: "Vim", pattern: /\bvim\b|vimrc/ },
  { group: "Zed", pattern: /\bzed editor\b|\bzed\b/ },
  { group: "Figma", pattern: /\bfigma\b/ },
  { group: "Framer", pattern: /\bframer\b/ },
  { group: "Canva", pattern: /\bcanva\b/ },
  { group: "Blender", pattern: /\bblender\b/ },
  { group: "React Native", pattern: /\breact native\b/ },
  { group: "React", pattern: /\breact(?:\.js)?\b/ },
  { group: "Vue", pattern: /\bvue(?:\.js)?\b/ },
  { group: "Next.js", pattern: /\bnext(?:\.js)?\b/ },
  { group: "Nuxt", pattern: /\bnuxt(?:\.js)?\b/ },
  { group: "Svelte", pattern: /\bsvelte(?:kit)?\b/ },
  { group: "Angular", pattern: /\bangular\b/ },
  { group: "Astro", pattern: /\bastro\b/ },
  { group: "Remix", pattern: /\bremix\b/ },
  { group: "Vite", pattern: /\bvite\b/ },
  { group: "Tailwind CSS", pattern: /\btailwind(?:css)?\b/ },
  { group: "CSS", pattern: /\bcss\b|css grid|flexbox|sass|scss|less\b/ },
  { group: "HTML", pattern: /\bhtml5?\b|web components?/ },
  { group: "TypeScript", pattern: /\btypescript|tsconfig\b/ },
  { group: "Node.js", pattern: /\bnode\.js\b|\bnodejs\b|\bnpm\b|\bpnpm\b|\byarn\b|\bbun\b/ },
  { group: "Deno", pattern: /\bdeno\b|deno\.land|jsr\.io/ },
  { group: "JavaScript", pattern: /\bjavascript\b|\becmascript\b|\besm\b/ },
  { group: "Python", pattern: /\bpython\b|pyenv|pip|conda|poetry|uv\b|jupyter|fastapi|django|flask|pytest\b/ },
  { group: "Jupyter", pattern: /\bjupyter\b|ipynb|notebook/ },
  { group: "Rust", pattern: /\brust\b|cargo|tokio|actix|axum|tauri\b/ },
  { group: "Go", pattern: /\bgolang\b|\bgo语言\b/ },
  { group: "Android", pattern: /\bandroid\b|android studio|jetpack compose/ },
  { group: "Java", pattern: /\bjava\b|spring boot|springcloud|maven|gradle\b/ },
  { group: "Kotlin", pattern: /\bkotlin\b|ktor\b/ },
  { group: "C++", pattern: /\bc\+\+\b|cppreference|cmake\b/ },
  { group: "C#", pattern: /\bc#\b|\.net\b|asp\.net|blazor|nuget\b/ },
  { group: "PHP", pattern: /\bphp\b|laravel|composer|packagist/ },
  { group: "Ruby", pattern: /\bruby\b|rails|rubygems/ },
  { group: "Dart", pattern: /\bdart\b|flutter|pub\.dev/ },
  { group: "Swift", pattern: /\bswift|swiftui|xcode\b/ },
  { group: "iOS", pattern: /\bios\b|iphone|ipad|swiftui|uikit|xcode\b/ },
  { group: "HarmonyOS", pattern: /harmonyos|鸿蒙|arkts|arkui|deveco/ },
  { group: "Docker", pattern: /\bdocker|dockerfile|docker compose|compose\.ya?ml\b/ },
  { group: "Kubernetes", pattern: /\bkubernetes|k8s|kubectl|helm\b/ },
  { group: "Terraform", pattern: /\bterraform\b|opentofu|hcl\b/ },
  { group: "Ansible", pattern: /\bansible\b/ },
  { group: "Nginx", pattern: /\bnginx\b/ },
  { group: "Git", pattern: /\bgit\b|版本控制/ },
  { group: "GitHub Actions", pattern: /github actions|\bgha\b/ },
  { group: "CI/CD", pattern: /\bci\/cd\b|\bjenkins\b|gitlab ci|circleci|travis ci|buildkite/ },
  { group: "Cloudflare", pattern: /\bcloudflare\b|workers? pages|cloudflare workers/ },
  { group: "Vercel", pattern: /\bvercel\b/ },
  { group: "Netlify", pattern: /\bnetlify\b/ },
  { group: "Render", pattern: /\brender\.com\b|\brender\b/ },
  { group: "Railway", pattern: /\brailway\b/ },
  { group: "AWS", pattern: /\baws\b|amazon web services|lambda\b|s3\b|ec2\b|cloudfront/ },
  { group: "Azure", pattern: /\bazure\b/ },
  { group: "Google Cloud", pattern: /\bgoogle cloud\b|\bgcp\b|cloud run|firebase/ },
  { group: "阿里云", pattern: /阿里云|aliyun|alibaba cloud/ },
  { group: "华为云", pattern: /华为云|huaweicloud/ },
  { group: "邮箱", pattern: /\b(gmail|outlook mail|yahoo mail|proton mail|protonmail|zoho mail|icloud mail)\b|qq邮箱|网易邮箱|163邮箱|126邮箱|阿里邮箱|企业邮箱|新浪邮箱|搜狐邮箱|邮箱|收件箱/ },
  { group: "聊天", pattern: /\b(whatsapp|telegram|google chat|slack|discord|microsoft teams|teams|skype|messenger|line|element|matrix|wecom)\b|微信网页版|网页版微信|企业微信|qq网页版|飞书|lark|钉钉|即时通讯|网页聊天|聊天/ },
  { group: "腾讯元宝", pattern: /腾讯元宝|\byuanbao\b/ },
  { group: "腾讯混元", pattern: /腾讯混元|\bhunyuan\b/ },
  { group: "腾讯云", pattern: /腾讯云|tencent cloud|cloud\.tencent/ },
  { group: "腾讯文档", pattern: /腾讯文档|docs\.qq\.com/ },
  { group: "腾讯会议", pattern: /腾讯会议|tencent meeting|voov meeting|meeting\.tencent/ },
  { group: "腾讯视频", pattern: /腾讯视频|tencent video|\bv\.qq\.com\b|tencentvideo/ },
  { group: "哔哩哔哩", pattern: /哔哩哔哩|bilibili|\bb站\b|bilibili\.com|b23\.tv/ },
  { group: "抖音", pattern: /抖音|douyin|douyin\.com|iesdouyin|tiktok|tiktok\.com/ },
  { group: "快手", pattern: /快手|kuaishou|kuaishou\.com|gifshow/ },
  { group: "小红书", pattern: /小红书|xiaohongshu|xhslink/ },
  { group: "爱奇艺", pattern: /爱奇艺|iqiyi/ },
  { group: "优酷", pattern: /优酷|youku/ },
  { group: "西瓜视频", pattern: /西瓜视频|ixigua/ },
  { group: "AcFun", pattern: /acfun|\bac\b/ },
  { group: "芒果 TV", pattern: /芒果tv|芒果 tv|mgtv/ },
  { group: "QQ 空间", pattern: /qq空间|qzone|user\.qzone|i\.qq\.com/ },
  { group: "邮箱", pattern: /qq邮箱|mail\.qq\.com/ },
  { group: "QQ 音乐", pattern: /qq音乐|y\.qq\.com|music\.qq\.com/ },
  { group: "微信公众平台", pattern: /微信公众平台|微信公众号|公众号后台|mp\.weixin\.qq\.com/ },
  { group: "企业微信", pattern: /企业微信|wecom|work\.weixin\.qq\.com/ },
  { group: "微信读书", pattern: /微信读书|weread/ },
  { group: "腾讯新闻", pattern: /腾讯新闻|news\.qq\.com|new\.qq\.com/ },
  { group: "Home Assistant", pattern: /\bhome assistant\b|\bhaos\b/ },
  { group: "Reddit", pattern: /\breddit\b|subreddit/ },
  { group: "Quora", pattern: /\bquora\b/ },
  { group: "知乎", pattern: /知乎|zhihu/ },
  { group: "V2EX", pattern: /\bv2ex\b/ },
  { group: "百度贴吧", pattern: /百度贴吧|\btieba\b/ },
  { group: "豆瓣", pattern: /豆瓣|douban/ },
  { group: "PostgreSQL", pattern: /\bpostgres(?:ql)?\b/ },
  { group: "Supabase", pattern: /\bsupabase\b/ },
  { group: "MySQL", pattern: /\bmysql\b|mariadb/ },
  { group: "Redis", pattern: /\bredis\b/ },
  { group: "MongoDB", pattern: /\bmongodb|mongo\b/ },
  { group: "SQLite", pattern: /\bsqlite\b/ },
  { group: "Elasticsearch", pattern: /\belasticsearch\b|\belastic search\b|elastic stack/ },
  { group: "ClickHouse", pattern: /\bclickhouse\b/ },
  { group: "Prisma", pattern: /\bprisma\b/ },
  { group: "API", pattern: /\b(rest api|graphql|grpc|openapi|swagger|webhook)\b|接口文档/ },
  { group: "GraphQL", pattern: /\bgraphql\b|apollo client|apollo server/ },
  { group: "Postman", pattern: /\bpostman\b/ },
  { group: "Apifox", pattern: /\bapifox\b/ },
  { group: "Sentry", pattern: /\bsentry\b/ },
  { group: "Grafana", pattern: /\bgrafana\b|prometheus/ },
  { group: "macOS", pattern: /\bmacos|launchd|homebrew|brew\b|快捷指令|自动操作/ },
  { group: "Windows", pattern: /\bwindows|powershell|wsl\b/ },
  { group: "Linux", pattern: /\blinux|ubuntu|debian|archlinux|systemd\b/ },
  { group: "Markdown", pattern: /\bmarkdown|mdx\b/ },
  { group: "Obsidian", pattern: /\bobsidian\b/ },
  { group: "Notion", pattern: /\bnotion\b/ },
  { group: "语雀", pattern: /语雀|yuque/ },
  { group: "飞书", pattern: /飞书|lark|feishu/ },
  { group: "项目管理", pattern: /\blinear\b|\bjira\b|\btrello\b|\basana\b|看板|需求管理|项目管理/ },
  { group: "LaTeX", pattern: /\blatex|overleaf\b/ },
  { group: "MacDown", pattern: /\bmacdown\b/ },
  { group: "MarkEdit", pattern: /\bmarkedit\b/ },
  { group: "LeetCode", pattern: /\bleetcode\b|力扣|算法题/ },
  { group: "论文", pattern: /论文|paper|arxiv|doi\.org|research|google scholar|谷歌学术/ },
  { group: "百科", pattern: /wikipedia|维基百科|百科/ },
  { group: "购物", pattern: /淘宝|天猫|京东|拼多多|amazon|ebay|1688|购物车|订单/ },
  { group: "金融", pattern: /股票|基金|行情|tradingview|yahoo finance|东方财富|雪球|加密货币|比特币|bitcoin|ethereum/ },
  { group: "文档", pattern: /文档|documentation|docs|manual|reference|手册/ },
  { group: "教程", pattern: /教程|入门|指南|guide|tutorial|learn/ },
  { group: "视频", pattern: /视频|直播|回放|\bvideo\b|\blive\b/ }
];

const SITE_PROPERTY_RULES = [
  { group: "AI 聊天", domains: ["chat.openai.com", "chatgpt.com", "claude.ai", "chat.deepseek.com", "kimi.moonshot.cn", "qwen.ai", "tongyi.com", "doubao.com", "gemini.google.com", "grok.com", "poe.com", "perplexity.ai", "copilot.microsoft.com", "meta.ai", "chat.mistral.ai", "phind.com", "you.com", "character.ai", "hunyuan.tencent.com", "yuanbao.tencent.com"] },
  { group: "AI API", domains: ["platform.openai.com", "api.openai.com", "anthropic.com", "platform.deepseek.com", "api-docs.deepseek.com", "aistudio.google.com", "ai.google.dev", "console.groq.com", "groq.com", "cohere.com", "together.ai", "openrouter.ai", "fireworks.ai", "siliconflow.cn", "modelscope.cn", "volcengine.com", "ark.cn-beijing.volces.com"] },
  { group: "AI 编程", domains: ["cursor.com", "codeium.com", "windsurf.com", "lovable.dev", "bolt.new", "v0.dev"] },
  { group: "AI 图像", domains: ["midjourney.com", "stability.ai", "runwayml.com", "civitai.com", "replicate.com"] },
  { group: "本地 AI", domains: ["ollama.com", "openwebui.com", "lmstudio.ai"] },
  { group: "AI 框架", domains: ["huggingface.co", "langchain.com", "python.langchain.com", "llamaindex.ai", "docs.llamaindex.ai", "dify.ai"] },
  { group: "代码托管", domains: ["github.com", "gitlab.com", "gitee.com", "bitbucket.org", "sourceforge.net", "codeberg.org"] },
  { group: "代码问答", domains: ["stackoverflow.com", "stackexchange.com", "superuser.com", "serverfault.com", "segmentfault.com"] },
  { group: "包管理", domains: ["npmjs.com", "jsr.io", "deno.land", "pypi.org", "crates.io", "pkg.go.dev", "mvnrepository.com", "packagist.org", "rubygems.org", "pub.dev", "nuget.org", "hub.docker.com"] },
  { group: "API 工具", domains: ["postman.com", "apifox.com", "insomnia.rest"] },
  { group: "监控运维", domains: ["sentry.io", "datadoghq.com", "grafana.com", "prometheus.io", "elastic.co"] },
  { group: "云服务", domains: ["cloud.tencent.com", "console.cloud.tencent.com", "aliyun.com", "console.aliyun.com", "alibabacloud.com", "huaweicloud.com", "cloud.huawei.com", "cloud.google.com", "console.cloud.google.com", "aws.amazon.com", "console.aws.amazon.com", "amazonaws.com", "azure.microsoft.com", "portal.azure.com", "digitalocean.com", "firebase.google.com"] },
  { group: "部署", domains: ["vercel.com", "netlify.com", "cloudflare.com", "render.com", "railway.app", "fly.io", "heroku.com"] },
  { group: "技术文档", domains: ["developer.mozilla.org", "docs.github.com", "learn.microsoft.com", "devdocs.io", "readthedocs.io", "developer.chrome.com", "developer.apple.com", "developer.apple.com.cn", "docs.openai.com", "docs.anthropic.com", "docs.cursor.com", "docs.deepseek.com", "docs.ollama.com", "docs.openwebui.com", "docs.dify.ai", "docs.n8n.io", "react.dev", "vuejs.org", "nextjs.org", "nuxt.com", "svelte.dev", "astro.build", "tailwindcss.com", "vite.dev", "nodejs.org", "docs.python.org", "doc.rust-lang.org", "go.dev", "developer.harmonyos.com"] },
  { group: "技术社区", domains: ["csdn.net", "blog.csdn.net", "download.csdn.net", "juejin.cn", "dev.to", "cnblogs.com", "oschina.net", "infoq.cn", "infoq.com", "v2ex.com", "news.ycombinator.com"] },
  { group: "论文研究", domains: ["arxiv.org", "scholar.google.com", "doi.org", "researchgate.net", "semanticscholar.org"] },
  { group: "百科资料", domains: ["wikipedia.org", "zh.wikipedia.org", "baike.baidu.com"] },
  { group: "在线学习", domains: ["coursera.org", "udemy.com", "edx.org", "khanacademy.org", "freecodecamp.org", "duolingo.com"] },
  { group: "刷题", domains: ["leetcode.com", "codeforces.com", "nowcoder.com", "acwing.com"] },
  { group: "文档协作", domains: ["docs.google.com", "office.com", "notion.so", "notion.site", "docs.qq.com", "yuque.com", "wolai.com", "quip.com", "overleaf.com"] },
  { group: "网盘", domains: ["drive.google.com", "icloud.com", "weiyun.com", "pan.baidu.com", "onedrive.live.com", "dropbox.com"] },
  { group: "日历会议", domains: ["calendar.google.com", "meet.google.com", "meeting.tencent.com", "voovmeeting.com", "zoom.us"] },
  { group: "项目管理", domains: ["linear.app", "trello.com", "asana.com", "jira.atlassian.com", "atlassian.com", "confluence.atlassian.com"] },
  { group: "自动化", domains: ["n8n.io", "zapier.com", "make.com", "ifttt.com"] },
  { group: "设计", domains: ["figma.com", "dribbble.com", "behance.net", "canva.com", "framer.com", "miro.com"] },
  { group: "邮箱", domains: ["mail.google.com", "gmail.com", "outlook.live.com", "outlook.office.com", "outlook.office365.com", "mail.qq.com", "exmail.qq.com", "mail.163.com", "mail.126.com", "mail.yahoo.com", "mail.proton.me", "protonmail.com", "mail.zoho.com", "mail.sina.com.cn", "mail.sohu.com", "mail.aliyun.com"] },
  { group: "聊天", domains: ["web.whatsapp.com", "telegram.org", "web.telegram.org", "webk.telegram.org", "webz.telegram.org", "chat.google.com", "messages.google.com", "app.slack.com", "slack.com", "discord.com", "teams.microsoft.com", "teams.live.com", "web.skype.com", "messenger.com", "web.line.me", "line.me", "app.element.io", "matrix.to", "wx.qq.com", "web.wechat.com", "im.qq.com", "work.weixin.qq.com", "web.dingtalk.com", "im.dingtalk.com", "feishu.cn", "larksuite.com"] },
  { group: "应用商店", domains: ["chromewebstore.google.com", "apps.apple.com", "appstoreconnect.apple.com"] },
  { group: "视频", domains: ["youtube.com", "youtu.be", "bilibili.com", "b23.tv", "bilibili.tv", "vimeo.com", "netflix.com", "iqiyi.com", "youku.com", "tencentvideo.com", "v.qq.com", "video.qq.com", "film.qq.com", "tv.apple.com", "douyin.com", "v.douyin.com", "iesdouyin.com", "tiktok.com", "kuaishou.com", "gifshow.com", "mgtv.com", "ixigua.com", "acfun.cn"] },
  { group: "直播", domains: ["live.bilibili.com", "live.douyin.com", "live.kuaishou.com", "twitch.tv"] },
  { group: "音乐", domains: ["music.apple.com", "podcasts.apple.com", "y.qq.com", "music.qq.com", "kg.qq.com", "spotify.com", "music.youtube.com"] },
  { group: "阅读", domains: ["weread.qq.com", "books.apple.com", "read.amazon.com"] },
  { group: "购物", domains: ["amazon.com", "amazon.cn", "taobao.com", "tmall.com", "jd.com", "pinduoduo.com", "1688.com", "ebay.com", "etsy.com"] },
  { group: "金融", domains: ["finance.yahoo.com", "tradingview.com", "bloomberg.com", "eastmoney.com", "xueqiu.com"] },
  { group: "新闻", domains: ["nytimes.com", "bbc.com", "reuters.com", "thepaper.cn", "36kr.com", "sspai.com", "news.qq.com", "new.qq.com", "sports.qq.com"] },
  { group: "社交", domains: ["x.com", "twitter.com", "facebook.com", "instagram.com", "weibo.com", "qzone.qq.com", "user.qzone.qq.com", "i.qq.com", "weixin.qq.com", "mp.weixin.qq.com", "xiaohongshu.com", "xhslink.com", "t.bilibili.com", "discussions.apple.com"] },
  { group: "论坛", domains: ["reddit.com", "old.reddit.com", "www.reddit.com", "quora.com", "zhihu.com", "zhuanlan.zhihu.com", "tieba.baidu.com", "douban.com", "groups.google.com", "discourse.org", "medium.com"] },
  { group: "搜索", domains: ["google.com", "bing.com", "baidu.com", "duckduckgo.com", "kagi.com", "search.brave.com", "startpage.com", "ecosia.org", "yandex.com", "search.yahoo.com", "sogou.com", "so.com", "mijisou.com", "quark.cn", "sm.cn", "naver.com", "searx.space"] },
  { group: "AI", domains: ["openai.com", "anthropic.com", "deepseek.com", "moonshot.cn", "mistral.ai", "replicate.com", "huggingface.co"] },
  { group: "办公", domains: ["work.weixin.qq.com", "feishu.cn", "larksuite.com", "slack.com"] },
  { group: "代码", domains: ["docker.com"] },
  { group: "文档", domains: ["microsoft.com"] }
];

const MULTI_PART_TLDS = new Set([
  "co.uk",
  "org.uk",
  "ac.uk",
  "gov.uk",
  "com.cn",
  "net.cn",
  "org.cn",
  "gov.cn",
  "com.au",
  "net.au",
  "org.au",
  "co.jp",
  "co.kr",
  "com.br",
  "com.mx",
  "com.sg",
  "com.hk",
  "com.tw"
]);

  return {
    WEAK_TITLE_GROUPS,
    FUNCTIONAL_TOPIC_STOP_WORDS,
    SOURCE_NAME_PATTERN,
    GROUP_COLORS,
    FUNCTIONAL_SITE_GROUPS,
    CLOUD_FINE_GRAINED_GROUPS,
    SEARCH_ENGINE_DOMAINS,
    DOMAIN_DISPLAY_NAMES,
    PRODUCT_DOMAIN_GROUPS,
    TITLE_TOPIC_RULES,
    SITE_PROPERTY_RULES,
    MULTI_PART_TLDS
  };
})();
